---
AWSTemplateFormatVersion: "2010-09-09"
Description: Resources to remediate CIS benchmark

Parameters:
  RoleName:
    Type: String
    Description: The name of the role

Resources:
  SupportRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: sts:AssumeRole
      Description: Permit AWS Support to access the account
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSSupportAccess
      RoleName: !Ref RoleName
