---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions the IAM boundaries used by CI

Parameters:
  BoundaryName:
    Type: String
    Description: The name of the Scope Permissions Boundary
    Default: Boundary
  TerraformStateROPolicyName:
    Type: String
    Description: The name of the Terraform State Read Only Policy
  TerraformStateRWPolicyName:
    Type: String
    Description: The name of the Terraform State Read Write Policy

Resources:
  # Used as the default IAM boundary
  Boundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref BoundaryName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAdminAccess
            Effect: Allow
            Action: "*"
            Resource: "*"
          - Sid: DenyAccess
            Effect: Deny
            Action:
              - "account:*"
              - "aws-portal:*"
              - "config:*"
              - "savingsplans:*"
            Resource: "*"
          - Sid: DenyPermBoundaryIAMPolicyAlteration
            Effect: Deny
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: DenyRemovalOfPermBoundaryFromAnyUserOrRole
            Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
              - iam:DeleteUserPermissionsBoundary
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:user/*"
              - !Sub "arn:aws:iam::$${AWS::AccountId}:role/*"
            Condition:
              StringEquals:
                "iam:PermissionsBoundary": !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: DenyAccessIfRequiredPermBoundaryIsNotBeingApplied
            Effect: Deny
            Action:
              - iam:PutRolePermissionsBoundary
              - iam:PutUserPermissionsBoundary
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:user/*"
              - !Sub "arn:aws:iam::$${AWS::AccountId}:role/*"
            Condition:
              StringNotEquals:
                "iam:PermissionsBoundary": !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: DenyRoleCreationWithOutPermBoundary
            Effect: Deny
            Action:
              - iam:CreateRole
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:role/*"
            Condition:
              StringNotEquals:
                "iam:PermissionsBoundary": !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: NoCIPolicyEdit
            Effect: Deny
            Action:
              - iam:CreatePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${TerraformStateRWPolicyName}"
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${TerraformStateROPolicyName}"
          - Sid: DenyRemoteState
            Effect: Deny
            Action:
              - dynamoDB:DeleteTable
            Resource:
              - !Sub "arn:aws:dynamodb::$${AWS::AccountId}:table/$${AWS::AccountId}-$${AWS::Region}-tflock"
          - Sid: DenyS3RemoteState
            Effect: Deny
            Action:
              - s3:DeleteBucket
            Resource:
              - !Sub "arn:aws:s3:::$${AWS::AccountId}-$${AWS::Region}-tfstate"
%{ if enable_tag_enforcement ~}
          - Sid: DenyNonTaggingRunInstances
            Effect: Deny
            Action:
              - ec2:RunInstances
            Resource:
              - arn:aws:ec2:*:*:instance/*
            Condition:
              ForAllValues:StringEquals:
                aws:TagKeys:
%{ for tag in tags ~}
                - ${tag}
%{ endfor ~}
          - Sid: DenyTaggingViolation
            Effect: Deny
            Action:
%{ for action in actions ~}
              - "${action}"
%{ endfor ~}
            Resource:
%{ for resource in resources ~} 
              - "${resource}"
%{ endfor ~}
            Condition:
              ForAllValues:StringEquals:
%{ for tag in tags ~}
                aws:TagKeys:
                  - ${tag}
%{ endfor ~}
              'Null':
%{ for tag in tags ~}
                aws:RequestTag/${tag}: 'true'
%{ endfor ~}
%{ endif ~}
