---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions the IAM boundaries used by CI

Parameters:
  BoundaryName:
    Type: String
    Description: The name of the Permissive Permissions Boundary
    Default: PermissivePermissionsBoundary
  TerraformStateROPolicyName:
    Type: String
    Description: The name of the Terraform State Read Only Policy
  TerraformStateRWPolicyName:
    Type: String
    Description: The name of the Terraform State Read Write Policy

Resources:
  Boundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref BoundaryName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAdminAccess
            Effect: Allow
            Action: "*"
            Resource: "*"
          - Sid: DenyAccess
            Effect: Deny
            Action:
              - "account:Delete*"
              - "account:Update*"
              - "aws-portal:Delete*"
              - "aws-portal:Update*"
              - "savingsplans:*"
            Resource: "*"
          - Sid: DenyPermBoundaryIAMPolicyAlteration
            Effect: Deny
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: NoCIPolicyEdit
            Effect: Deny
            Action:
              - iam:CreatePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${TerraformStateRWPolicyName}"
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${TerraformStateROPolicyName}"
          - Sid: ProtectDynamoDBRemoteStateLock
            Effect: Deny
            Action:
              - dynamoDB:DeleteTable
            Resource:
              - !Sub "arn:aws:dynamodb:*:$${AWS::AccountId}:table/$${AWS::AccountId}-*-tflock"
          - Sid: ProtectS3RemoteState
            Effect: Deny
            Action:
              - s3:DeleteBucket
            Resource:
              - !Sub "arn:aws:s3:::$${AWS::AccountId}-*-tfstate"
%{ if enable_tag_enforcement ~}
          - Sid: DenyTagRunInstances
            Effect: Deny
            Action:
              - ec2:RunInstances
            Resource:
              - "arn:aws:ec2:*:*:instance/*"
            Condition:
              ForAllValues:StringEquals:
                aws:TagKeys:
%{ for tag in tags ~}
                  - ${tag}
%{ endfor ~}
          - Sid: DenyTagRunInstancesResources
            Effect: Deny
            Action:
              - ec2:RunInstances
            Resource:
              - arn:aws:ec2:*:*:key-pair/*
              - arn:aws:ec2:*:*:launch-template/*
              - arn:aws:ec2:*:*:subnet/*
            Condition:
              'Null':
%{ for tag in tags ~}
                aws:ResourceTag/${tag}: 'true'
%{ endfor ~}
          - Sid: DenyTaggingViolation
            Effect: Deny
            Action:
%{ for action in actions ~}
              - "${action}"
%{ endfor ~}
            Resource:
%{ for resource in resources ~} 
              - "${resource}"
%{ endfor ~}
            Condition:
              ForAllValues:StringEquals:
                aws:TagKeys:
%{ for tag in tags ~}
                  - ${tag}
%{ endfor ~}
              'Null':
%{ for tag in tags ~}
                aws:RequestTag/${tag}: 'true'
%{ endfor ~}
%{ endif ~}
