---
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisions the IAM boundary used to enforce tagging policies

Parameters:
  BoundaryName:
    Type: String
    Description: The name of the Permissive Permissions Boundary
    Default: lza-tagging-boundary

Resources:
  Boundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref BoundaryName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAdminAccess
            Effect: Allow
            Action: "*"
            Resource: "*"
          - Sid: DenyPermBoundaryIAMPolicyAlteration
            Effect: Deny
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - !Sub "arn:aws:iam::$${AWS::AccountId}:policy/$${BoundaryName}"
          - Sid: EnforceTaggingPolicy
            Effect: Deny 
            Action: 
%{ for action in actions ~}
              - "${action}"
%{ endfor ~}
            Resource:
%{ for resource in resources ~} 
              - "${resource}"
%{ endfor ~}
            Condition: 
                Null: 
%{ for tag in tags ~}
                  "aws:RequestTag/${tag}": "true"
%{ endfor ~} 
